name: Pre-requisites
description: Setup Pre-requisites for Role Manager
inputs:
  token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: composite
  steps:
    - name: Checkout role-manager
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ inputs.token }}
        persist-credentials: false

    - name: Setup pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      with:
        run_install: false

    - name: Use node@22
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: 22.18.0
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
